---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: httpd-rc
 labels:
  author: Chaithanya
  type: frontend
spec:
 replicas: 5
 selector:
  matchLabels:
   type: frontend
 template:
  metadata:
   name: httpd-pod
   labels:
    type: frontend
  spec:
   containers:
    - name: webserver
      image: httpd
      ports:
       - containerPort: 80
         hostPort: 8080
