---
apiVersion: v1
kind: ReplicationController
metadata:
 name: nginx-rc
 labels:
  author: Chaithanya
spec:
 replicas: 3
 template:
  metadata:
   name: nginx-pod
   labels:
    author: intelliqit
  spec:
   containers:
    - name: appserver
      image: nginx
      ports:
       - containerPort: 80
         hostPort: 9999
